name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: echo
        run: echo hello
